# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='rpc_package',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10helloworld.proto\x12\x0brpc_package\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0c\x41gainRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nAgainReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x92\x01\n\x07Greeter\x12@\n\x08SayHello\x12\x19.rpc_package.HelloRequest\x1a\x17.rpc_package.HelloReply\"\x00\x12\x45\n\rSayHelloAgain\x12\x19.rpc_package.AgainRequest\x1a\x17.rpc_package.AgainReply\"\x00\x62\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='rpc_package.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rpc_package.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=61,
)


_AGAINREQUEST = _descriptor.Descriptor(
  name='AgainRequest',
  full_name='rpc_package.AgainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='rpc_package.AgainRequest.city', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=91,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='rpc_package.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_package.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=122,
)


_AGAINREPLY = _descriptor.Descriptor(
  name='AgainReply',
  full_name='rpc_package.AgainReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_package.AgainReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['AgainRequest'] = _AGAINREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['AgainReply'] = _AGAINREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

AgainRequest = _reflection.GeneratedProtocolMessageType('AgainRequest', (_message.Message,), {
  'DESCRIPTOR' : _AGAINREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.AgainRequest)
  })
_sym_db.RegisterMessage(AgainRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

AgainReply = _reflection.GeneratedProtocolMessageType('AgainReply', (_message.Message,), {
  'DESCRIPTOR' : _AGAINREPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.AgainReply)
  })
_sym_db.RegisterMessage(AgainReply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='rpc_package.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=156,
  serialized_end=302,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='rpc_package.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayHelloAgain',
    full_name='rpc_package.Greeter.SayHelloAgain',
    index=1,
    containing_service=None,
    input_type=_AGAINREQUEST,
    output_type=_AGAINREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
